// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierMicroservice.Models;

#nullable disable

namespace SupplierMicroservice.Migrations
{
    [DbContext(typeof(SPContext))]
    partial class SPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SupplierMicroservice.Models.Supplier", b =>
                {
                    b.Property<string>("SID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Feedback")
                        .HasColumnType("int");

                    b.Property<string>("SAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SEmail")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("SMobile")
                        .HasColumnType("bigint");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("SupplierMicroservice.Models.Supplier_Part", b =>
                {
                    b.Property<string>("PID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("PDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PQuantity")
                        .HasColumnType("int");

                    b.HasKey("PID");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("SupplierMicroservice.Models.SupplierPart", b =>
                {
                    b.Property<string>("SID")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PID")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SID", "PID");

                    b.HasIndex("PID");

                    b.ToTable("SupplierParts");
                });

            modelBuilder.Entity("SupplierMicroservice.Models.SupplierPart", b =>
                {
                    b.HasOne("SupplierMicroservice.Models.Supplier_Part", "Supplier_Part")
                        .WithMany("SuppliersLink")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplierMicroservice.Models.Supplier", "Supplier")
                        .WithMany("PartsLink")
                        .HasForeignKey("SID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Supplier_Part");
                });

            modelBuilder.Entity("SupplierMicroservice.Models.Supplier", b =>
                {
                    b.Navigation("PartsLink");
                });

            modelBuilder.Entity("SupplierMicroservice.Models.Supplier_Part", b =>
                {
                    b.Navigation("SuppliersLink");
                });
#pragma warning restore 612, 618
        }
    }
}
